### ISSUE TITLE
In vue Failed when connecting: Unknown init state (state: )

### ISSUE THREAD

**Issue by erayakgunn** [daizhiyu/vnc-server#1]
in vue there is an error Failed when connecting: Unknown init state (state: )
it does not show the noVnc page

**Comment by daizhiyu** [comment]
![image](https://github.com/daizhiyu/vnc-server/assets/8065015/d0d84ecc-fdb1-4c0f-8fdf-2f220c6d0af2)

![image](https://github.com/daizhiyu/vnc-server/assets/8065015/92f94c2c-5550-4704-9bed-ce34597d6436)

![image](https://github.com/daizhiyu/vnc-server/assets/8065015/a912ad95-a3bc-4d2d-a127-2173a342186e)


Could you please confirm if the WebSocket is enabled as shown in the picture above?

**Comment by 277584579** [comment]
我遇到的是同样的问题访问访问 http://127.0.0.1:9000/vnc.html
![image](https://github.com/daizhiyu/vnc-server/assets/22782505/e18b1875-27e6-4384-912f-10cff2f87587)
然后浏览器端
![image](https://github.com/daizhiyu/vnc-server/assets/22782505/55c6a5dd-618e-4d6b-b2da-3b96ca576c67)
![image](https://github.com/daizhiyu/vnc-server/assets/22782505/8adf9c8e-9ea0-4d5c-a520-1c649e98b9c8)

**Comment by 277584579** [comment]
![image](https://github.com/daizhiyu/vnc-server/assets/22782505/25d18a92-07e3-4660-a568-e18d50f0a9be)
访问 http://127.0.0.1:9000/vnc.html时候显示没链接上，我是按照文档来写的

**Comment by 277584579** [comment]
![image](https://github.com/daizhiyu/vnc-server/assets/22782505/75189010-99de-41e5-ae53-eb2d11aa3ecb)
按照文档写的，同样的问题

**Comment by 277584579** [comment]
按照文档去写http://127.0.0.1:9000/vnc.html能正常访问，也能操作，但是vue项目端报错跟他的一样
![image](https://github.com/daizhiyu/vnc-server/assets/22782505/3e0f9351-5b70-4f00-b4ea-3dac7e7aa78b)

**Comment by daizhiyu** [comment]
onMounted(()=>{
  rfbServer.value=new RFB(rfbRef.value,vncConfig.websockify);
    setTimeout(()=>{
      connect();
    },10)
}) 我试了下 这个创建连接得 延时一下    http://127.0.0.1:9000/vnc.html 打开这个页面渲染需要一点时间 ， 直接去 sendCredentials 就报哪个错了 得延时下 ~~ 我的之前的做法是 有个按钮点击 才开始认证 所以没发现这个问题
