### ISSUE TITLE
请问功能有更详细的描述吗，或在线demo？

### ISSUE THREAD

**Issue by AbstractWorld** [daizhiyu/vnc-server#2]
请问是必须每一台被控制的host都部署一次vnc-server，还是只需部署在一台局域网内的设备上，其余被控host打开vnc服务即可？
用户的网段可以和被控网段隔离吗？

**Comment by daizhiyu** [comment]
您好！对于 VNC，通常情况下，需要在每台希望远程控制的设备上都部署一个 VNC 服务器。这样，您才能通过 VNC 客户端连接到每台设备并进行控制。 
至于您的第二个问题，被控制的主机和控制主机的网络段可以是隔离的。只要网络允许从控制主机到被控制主机的访问即可。如果网络隔离，您可能需要通过网络配置或者VPN等方式来实现访问。

**Comment by daizhiyu** [comment]
如果是需要远程的机器 一般是需要安装  UltraVNC_1_3_42_X64_Setup.exe  当然这个是win版本的， 这个是vnc 的服务， 控制的 按照 demo 来就行  在线demo 涉及有点多 故没有弄，不好意思~
